# https://docs.docker.com/compose/compose-file/05-services/
services:

  app:
    image: golang
    entrypoint:
      - sleep
      - infinity
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - go:/go

volumes:
  go:
    external: true
